server:
  port: 8888
  servlet:
    session:
      tracking-modes: cookie
spring:
  datasource:
    url: "to-be-replace"
    username: "to-be-replace"
    password: "to-be-replace"
  jpa:
    hibernate:
      ddl-auto: validate
  mustache:
    check-template-location: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: "to-be-replace"
    password: "to-be-replace"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB
vaadin:
  launch-browser: true
  whitelisted-packages: com.vaadin,org,vaadin,dev.hilla,cz.upce.fei.dt
aws:
  region: "to-be-replace"
  access-key-id: "to-be-replace"
  secret-access-key: "to-be-replace"
  s3:
    buckets:
      contract: "to-be-replace"